# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-06-06 11:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news_board', '0002_auto_20250515_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_board.News')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
